=begin
#API v1

#FormAPI is a service that helps you fill out and sign PDF templates.

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.0-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for FormAPI::Templatesv2TemplateDocumentMetadata
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'Templatesv2TemplateDocumentMetadata' do
  before do
    # run before each test
    @instance = FormAPI::Templatesv2TemplateDocumentMetadata.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Templatesv2TemplateDocumentMetadata' do
    it 'should create an instance of Templatesv2TemplateDocumentMetadata' do
      expect(@instance).to be_instance_of(FormAPI::Templatesv2TemplateDocumentMetadata)
    end
  end
  describe 'test attribute "filename"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "size"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "mime_type"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["application/pdf"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.mime_type = value }.not_to raise_error
      # end
    end
  end

end
