=begin
#API v1

#FormAPI is a service that helps you fill out and sign PDF templates.

OpenAPI spec version: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.0-SNAPSHOT

=end

# Common files
require 'form_api/api_client'
require 'form_api/api_error'
require 'form_api/version'
require 'form_api/configuration'

# Models
require 'form_api/models/authentication_error'
require 'form_api/models/authentication_success_response'
require 'form_api/models/combine_pdfs_data'
require 'form_api/models/combined_submission'
require 'form_api/models/combined_submission_action'
require 'form_api/models/combined_submission_data'
require 'form_api/models/create_combined_submission_response'
require 'form_api/models/create_custom_file_data'
require 'form_api/models/create_custom_file_response'
require 'form_api/models/create_folder_data'
require 'form_api/models/create_submission_batch_response'
require 'form_api/models/create_submission_batch_submissions_response'
require 'form_api/models/create_submission_data_request_data'
require 'form_api/models/create_submission_data_request_token_response'
require 'form_api/models/create_submission_data_request_token_response_token'
require 'form_api/models/create_submission_response'
require 'form_api/models/create_template_data'
require 'form_api/models/custom_file'
require 'form_api/models/error'
require 'form_api/models/folder'
require 'form_api/models/folders_folder'
require 'form_api/models/invalid_request'
require 'form_api/models/move_folder_data'
require 'form_api/models/move_template_data'
require 'form_api/models/pending_template'
require 'form_api/models/rename_folder_data'
require 'form_api/models/submission'
require 'form_api/models/submission_action'
require 'form_api/models/submission_batch'
require 'form_api/models/submission_batch_data'
require 'form_api/models/submission_data'
require 'form_api/models/submission_data_batch_request'
require 'form_api/models/submission_data_request'
require 'form_api/models/template'
require 'form_api/models/templatesv2_template'
require 'form_api/models/templatesv2_template_document'
require 'form_api/models/templatesv2_template_document_metadata'
require 'form_api/models/update_data_request_response'
require 'form_api/models/update_submission_data_request_data'

# APIs
require 'form_api/api/pdf_api'

# Custom client
require 'form_api/api/client'

module FormAPI
  class << self
    # Customize default settings for the SDK using block.
    #   FormAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
